from app.models import db, ProductTag


def seed_productTags():
 adelae= ProductTag(products_id=1, tags_id=5 )
 briggsiana= ProductTag(products_id=2 , tags_id=1 )
 agnataRed= ProductTag(products_id=3 , tags_id=4 )
 alpina= ProductTag(products_id=4 , tags_id=7 )
 BainesKloof= ProductTag(products_id=5 , tags_id=4 )
 Cephalotus= ProductTag(products_id=6 , tags_id= )
 falconeri= ProductTag(products_id=7 , tags_id=4 )
 fulva= ProductTag(products_id=8 , tags_id=4 )
 gramogolensis= ProductTag(products_id=9 , tags_id=4 )
 hamata= ProductTag(products_id=10 , tags_id= )
 lanata= ProductTag(products_id=11 , tags_id=4 )
 LotusEater= ProductTag(products_id=12 , tags_id=4 )
 madagascariensis= ProductTag(products_id=13 , tags_id=4 )
 Microdent= ProductTag(products_id=14 , tags_id=3 )
 paradoxa_TYPE= ProductTag(products_id=15 , tags_id=4 )
 petiolaris= ProductTag(products_id=16, tags_id=4 )
 splashPage= ProductTag(products_id=17 , tags_id=1 )
 Porcelain= ProductTag(products_id=18 , tags_id=1 )
 potosiensis= ProductTag(products_id=19, tags_id=4 )
 slackii= ProductTag(products_id=20 , tags_id=4 )
 yuccaDo1713= ProductTag(products_id=21 , tags_id=4 )
 nelumbifoliaxreniformis= ProductTag(products_id=22 , tags_id=7 )

 db.session.add(adelae)
 db.session.add(briggsiana)
 db.session.add(agnataRed)
 db.session.add(alpina)
 db.session.add(BainesKloof)
 db.session.add(Cephalotus)
 db.session.add(falconeri)
 db.session.add(fulva)
 db.session.add(gramogolensis)
 db.session.add(hamata)
 db.session.add(lanata)
 db.session.add(LotusEater)
 db.session.add(madagascariensis)
 db.session.add(Microdent)
 db.session.add(paradoxa_TYPE)
 db.session.add(petiolaris)
 db.session.add(splashPage)
 db.session.add(Porcelain)
 db.session.add(potosiensis)
 db.session.add(slackii)
 db.session.add(yuccaDo1713)
 db.session.add(nelumbifoliaxreniformis)
 db.session.commit()

def undo_productTags():
    db.session.execute('TRUNCATE productTags CASCADE;')
    db.session.execute("ALTER SEQUENCE productTags_id_seq RESTART WITH 1")
    db.session.commit()
