"""added name column on tag

Revision ID: 82498a12f4f1
Revises: 2c0a2a366e22
Create Date: 2021-03-03 00:51:42.711151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82498a12f4f1'
down_revision = '2c0a2a366e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('name', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tags', 'name')
    # ### end Alembic commands ###
