"""changed seeders took out faker

Revision ID: 85061566de63
Revises: 82498a12f4f1
Create Date: 2021-03-04 12:21:11.884128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85061566de63'
down_revision = '82498a12f4f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'name')
    # ### end Alembic commands ###
