"""changes to produc tag joins model

Revision ID: 0554721e20fd
Revises: 85061566de63
Create Date: 2021-03-04 13:29:32.223809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0554721e20fd'
down_revision = '85061566de63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productTags', 'reviews')
    op.drop_column('productTags', 'ratings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productTags', sa.Column('ratings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('productTags', sa.Column('reviews', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
